phrase = 'Don`t panic!'
plist = list(phrase)
print(phrase)
print(plist)
print(plist[:5:])
print(plist[6:11:])
print(plist[::11])

plist.pop(0)
plist.remove('`')
plist.remove(' ')
plist.insert(2, ' ')
for aa in range(5):
    plist.pop(-1)
plist.insert(4, 'a')
print(plist)
new_phrase = ''.join(plist)
print(new_phrase)

first = [1,2,3,4,5]
print(first)
second = (first)
print(second)
second.append(6)
print(second)
print(first)
third = second.copy()
print(third)
third.append(7)
print(first, second, third)
print(third[::2])